name: "Gabriella O Estevam"
description: "My Website"

url: "https://gestevam.github.io"

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/blog/page:num"


collections:
  publications:
    output: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
